import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EnvInfo from "./components/EnvInfo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Load runtime environment configuration */}
        <script src="/env-config.js" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <EnvInfo />
      </body>
    </html>
  );
}
